"""Data models module for Waffen-Solver."""

from waffen_solver.models.error import (
    Error,
    RawError,
    StackTrace,
    StackFrame,
    ErrorType,
    SeverityLevel,
    EnvironmentInfo,
)
from waffen_solver.models.solution import (
    Solution,
    RankedSolution,
    CodeImplementation,
    TradeOffAnalysis,
    ComplexityLevel,
    RiskLevel,
    TimeEstimate,
    TestStrategy,
)
from waffen_solver.models.context import (
    Context,
    CodebaseContext,
    SessionContext,
    EnvironmentContext,
    AggregatedContext,
    ContextSource,
)
from waffen_solver.models.analysis_result import (
    AnalysisResult,
    RootCause,
    Factor,
    CodeSegment,
    PastIssue,
    ErrorAnalysis,
)
from waffen_solver.models.git_info import (
    GitContext,
    Commit,
    Change,
    BlameInfo,
    FileHistory,
    FragileArea,
    Author,
    DiffAnalysis,
)

__all__ = [
    "Error",
    "RawError",
    "StackTrace",
    "StackFrame",
    "ErrorType",
    "SeverityLevel",
    "EnvironmentInfo",
    "Solution",
    "RankedSolution",
    "CodeImplementation",
    "TradeOffAnalysis",
    "ComplexityLevel",
    "RiskLevel",
    "TimeEstimate",
    "TestStrategy",
    "Context",
    "CodebaseContext",
    "SessionContext",
    "EnvironmentContext",
    "AggregatedContext",
    "ContextSource",
    "AnalysisResult",
    "RootCause",
    "Factor",
    "CodeSegment",
    "PastIssue",
    "ErrorAnalysis",
    "GitContext",
    "Commit",
    "Change",
    "BlameInfo",
    "FileHistory",
    "FragileArea",
    "Author",
    "DiffAnalysis",
]
